name             'letsencrypt-boulder-server'
maintainer       'Patrick Connolly (patcon)'
maintainer_email 'patrick.c.connolly@gmail.com'
license          'MIT'
description      'Installs/Configures letsencrypt-boulder-server'
long_description 'Installs/Configures letsencrypt-boulder-server'
version          '0.1.0'
