name             'boulder_test'
maintainer       'Oregon State University'
maintainer_email 'chef@osuosl.org'
license          'Apache 2.0'
description      'Installs/Configures boulder_test'
long_description ''
version          '0.1.0'
depends          'apache2'
depends          'osl-acme'
depends          'osl-apache'
